# -*- coding: utf-8 -*-
"""Data analysis1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw0RLITPuN2PSl5sPXe4_QMTrW3yY44O
"""

! pip install numpy
! pip install pandas
! pip install seaborn
! pip install matplotlib
! pip install numpy scipy
! pip install scikit-learn
! pip install openpyxl

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mp
import sklearn as sk

import pandas as pd
df= pd.read_csv('StudentPerformanceFactors.csv')
print(df)

!ls /content/

print(df.shape)

print(df.columns)

print (df[["Hours_Studied", "Attendance", "Exam_Score"]])
pd.set_option("display.max_rows", None)

df[["Hours_Studied", "Attendance", "Exam_Score"]].to_excel( "Studentfactors.xlsx",index=False)

print(df[df["Exam_Score"]>70])

df[["Hours_Studied", "Attendance", "Exam_Score"]].to_excel( "Studentfactors.xlsx",index=False)

df.groupby("Gender")[['Hours_Studied','Attendance','Exam_Score']].mean()

import seaborn as sns
import matplotlib.pyplot as plt
sns.scatterplot(x='Hours_Studied', y='Exam_Score', data=df, color='green')
sns.regplot(x='Hours_Studied', y='Exam_Score', data=df, color='green')
plt.title("Hours Studied vs Exam_Score")
plt.show()



correlation = df['Attendance'].corr(df['Exam_Score'])
print(f"Correlation between Attendance and Exam_Score: {correlation:.2f}")

import seaborn as sns
import matplotlib.pyplot as plt
sns.scatterplot(x='Attendance', y='Exam_Score', data=df, color='blue')
sns.regplot(x='Attendance', y='Exam_Score', data=df, color='blue', scatter_kws={'alpha':0.3})
plt.title("Attendance vs Exam_Score")
plt.xlabel("Attendance")
plt.ylabel("Exam_Score")
plt.show()

"""# New Section"""

import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
print (df)
X = df[['Attendance']]
y = df['Exam_Score']

model = LinearRegression()
model.fit(X, y)
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict Exam Score for 65 Hours
predicted_score = model.predict([[65]])
print("Predicted Exam Score for 65% Attendance:", predicted_score[0])



import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
print (df)
X = df[['Attendance']]
y = df['Exam_Score']

model = LinearRegression()
model.fit(X, y)
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict Exam Score for 65 Hours
predicted_score = model.predict([[65]])
print("Predicted Exam Score for 65% Attendance:", predicted_score[0])



import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
print (df)
X = df[['Attendance']]
y = df['Exam_Score']

model = LinearRegression()
model.fit(X, y)
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict Exam Score for 65 Hours
predicted_score = model.predict([[65]])
print("Predicted Exam Score for 65% Attendance:", predicted_score[0])



import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
print (df)
X = df[['Attendance']]
y = df['Exam_Score']

model = LinearRegression()
model.fit(X, y)
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict Exam Score for 65 Hours
predicted_score = model.predict([[65]])
print("Predicted Exam Score for 65% Attendance:", predicted_score[0])



import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
print (df)
X = df[['Attendance']]
y = df['Exam_Score']

model = LinearRegression()
model.fit(X, y)
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict Exam Score for 80 Hours
predicted_score = model.predict([[80]])
print("Predicted Exam Score for 80% Attendance:", predicted_score[0])

#Test whether Peer Influence and Motivation Level are related
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
contingency_table = pd.crosstab(df['Motivation_Level'], df['Gender'])

print("Contingency Table:")
print(contingency_table)
from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(contingency_table)
n = contingency_table.sum().sum()  # total sample size
cramers_v = np.sqrt(chi2 / (n * (min(contingency_table.shape)-1)))

print("Cramer's V:", cramers_v)



print("\nChi-Square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("P-value:", p)
print("\nExpected Frequencies Table:")
print(expected)



#Test whether Peer Influence and Motivation Level are related
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import sklearn
import numpy as np
df= pd.read_csv('StudentPerformanceFactors.csv')
contingency_table = pd.crosstab(df['Motivation_Level'], df['Peer_Influence'])
sns.heatmap(contingency_table, annot=True, cmap="Blues", fmt="d")

plt.title("Motivation vs Peer Influence")
plt.ylabel("Motivation Level")
plt.xlabel("Peer Influence")
plt.show()
